/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppSessionsIndexRouteImport } from './routes/_app/sessions/index'
import { Route as AppRecordingsIndexRouteImport } from './routes/_app/recordings/index'
import { Route as AppProfilesIndexRouteImport } from './routes/_app/profiles/index'
import { Route as AppPluginsIndexRouteImport } from './routes/_app/plugins/index'
import { Route as AppMonitoringIndexRouteImport } from './routes/_app/monitoring/index'
import { Route as AppAutorunsIndexRouteImport } from './routes/_app/autoruns/index'
import { Route as AppMonitoringSessionIdRouteImport } from './routes/_app/monitoring/$sessionId'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppSessionsIndexRoute = AppSessionsIndexRouteImport.update({
  id: '/sessions/',
  path: '/sessions/',
  getParentRoute: () => AppRoute,
} as any)
const AppRecordingsIndexRoute = AppRecordingsIndexRouteImport.update({
  id: '/recordings/',
  path: '/recordings/',
  getParentRoute: () => AppRoute,
} as any)
const AppProfilesIndexRoute = AppProfilesIndexRouteImport.update({
  id: '/profiles/',
  path: '/profiles/',
  getParentRoute: () => AppRoute,
} as any)
const AppPluginsIndexRoute = AppPluginsIndexRouteImport.update({
  id: '/plugins/',
  path: '/plugins/',
  getParentRoute: () => AppRoute,
} as any)
const AppMonitoringIndexRoute = AppMonitoringIndexRouteImport.update({
  id: '/monitoring/',
  path: '/monitoring/',
  getParentRoute: () => AppRoute,
} as any)
const AppAutorunsIndexRoute = AppAutorunsIndexRouteImport.update({
  id: '/autoruns/',
  path: '/autoruns/',
  getParentRoute: () => AppRoute,
} as any)
const AppMonitoringSessionIdRoute = AppMonitoringSessionIdRouteImport.update({
  id: '/monitoring/$sessionId',
  path: '/monitoring/$sessionId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/profile': typeof AppProfileRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/monitoring/$sessionId': typeof AppMonitoringSessionIdRoute
  '/autoruns/': typeof AppAutorunsIndexRoute
  '/monitoring/': typeof AppMonitoringIndexRoute
  '/plugins/': typeof AppPluginsIndexRoute
  '/profiles/': typeof AppProfilesIndexRoute
  '/recordings/': typeof AppRecordingsIndexRoute
  '/sessions/': typeof AppSessionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/profile': typeof AppProfileRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/monitoring/$sessionId': typeof AppMonitoringSessionIdRoute
  '/autoruns': typeof AppAutorunsIndexRoute
  '/monitoring': typeof AppMonitoringIndexRoute
  '/plugins': typeof AppPluginsIndexRoute
  '/profiles': typeof AppProfilesIndexRoute
  '/recordings': typeof AppRecordingsIndexRoute
  '/sessions': typeof AppSessionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_app/profile': typeof AppProfileRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_app/': typeof AppIndexRoute
  '/_app/monitoring/$sessionId': typeof AppMonitoringSessionIdRoute
  '/_app/autoruns/': typeof AppAutorunsIndexRoute
  '/_app/monitoring/': typeof AppMonitoringIndexRoute
  '/_app/plugins/': typeof AppPluginsIndexRoute
  '/_app/profiles/': typeof AppProfilesIndexRoute
  '/_app/recordings/': typeof AppRecordingsIndexRoute
  '/_app/sessions/': typeof AppSessionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/profile'
    | '/login'
    | '/register'
    | '/monitoring/$sessionId'
    | '/autoruns/'
    | '/monitoring/'
    | '/plugins/'
    | '/profiles/'
    | '/recordings/'
    | '/sessions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/profile'
    | '/login'
    | '/register'
    | '/monitoring/$sessionId'
    | '/autoruns'
    | '/monitoring'
    | '/plugins'
    | '/profiles'
    | '/recordings'
    | '/sessions'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_app/profile'
    | '/_auth/login'
    | '/_auth/register'
    | '/_app/'
    | '/_app/monitoring/$sessionId'
    | '/_app/autoruns/'
    | '/_app/monitoring/'
    | '/_app/plugins/'
    | '/_app/profiles/'
    | '/_app/recordings/'
    | '/_app/sessions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sessions/': {
      id: '/_app/sessions/'
      path: '/sessions'
      fullPath: '/sessions/'
      preLoaderRoute: typeof AppSessionsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recordings/': {
      id: '/_app/recordings/'
      path: '/recordings'
      fullPath: '/recordings/'
      preLoaderRoute: typeof AppRecordingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profiles/': {
      id: '/_app/profiles/'
      path: '/profiles'
      fullPath: '/profiles/'
      preLoaderRoute: typeof AppProfilesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/plugins/': {
      id: '/_app/plugins/'
      path: '/plugins'
      fullPath: '/plugins/'
      preLoaderRoute: typeof AppPluginsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/monitoring/': {
      id: '/_app/monitoring/'
      path: '/monitoring'
      fullPath: '/monitoring/'
      preLoaderRoute: typeof AppMonitoringIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/autoruns/': {
      id: '/_app/autoruns/'
      path: '/autoruns'
      fullPath: '/autoruns/'
      preLoaderRoute: typeof AppAutorunsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/monitoring/$sessionId': {
      id: '/_app/monitoring/$sessionId'
      path: '/monitoring/$sessionId'
      fullPath: '/monitoring/$sessionId'
      preLoaderRoute: typeof AppMonitoringSessionIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppProfileRoute: typeof AppProfileRoute
  AppIndexRoute: typeof AppIndexRoute
  AppMonitoringSessionIdRoute: typeof AppMonitoringSessionIdRoute
  AppAutorunsIndexRoute: typeof AppAutorunsIndexRoute
  AppMonitoringIndexRoute: typeof AppMonitoringIndexRoute
  AppPluginsIndexRoute: typeof AppPluginsIndexRoute
  AppProfilesIndexRoute: typeof AppProfilesIndexRoute
  AppRecordingsIndexRoute: typeof AppRecordingsIndexRoute
  AppSessionsIndexRoute: typeof AppSessionsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppProfileRoute: AppProfileRoute,
  AppIndexRoute: AppIndexRoute,
  AppMonitoringSessionIdRoute: AppMonitoringSessionIdRoute,
  AppAutorunsIndexRoute: AppAutorunsIndexRoute,
  AppMonitoringIndexRoute: AppMonitoringIndexRoute,
  AppPluginsIndexRoute: AppPluginsIndexRoute,
  AppProfilesIndexRoute: AppProfilesIndexRoute,
  AppRecordingsIndexRoute: AppRecordingsIndexRoute,
  AppSessionsIndexRoute: AppSessionsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
